set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $DB_READONLY_USER WITH PASSWORD '$DB_READONLY_PASSWORD';
  GRANT SELECT ON ALL TABLES IN SCHEMA public TO $DB_READONLY_USER;
EOSQL